# Site settings
title: 静以致远
email: muxinxin@yeah.net
description: "See it, believe it, act on it！"
baseurl: ""
url: "http://www.muxinxin.top"
twitter_username: jekyllrb
github_username:  pressuretree

# Build settings
markdown: kramdown
permalink: pretty
