# Site settings
title: 静以致远
email: muxinxin@yeah.net
description: "这是一个很有意思的地方，我使用Jekyll搭建的一个静态博客，很高兴能成功访问到！"
baseurl: ""
url: "http://www.muxinxin.top"
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
permalink: pretty
